# Copyright (C) 2021-2026, James Flamino


# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#
#http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


import sys
import os

import CIcython # Use Alexandre Bovet's edited CI code

import time
import pickle
import graph_tool.all as gt

import numpy as np

# Edit to point
OUT_PATH = '../data/ci_output' #'/path/to/generate_ci/graphs'

# point these to where the <bias>_<year>.gt graphs generated by generate_graphs.py live
GRAPH_DIR_2016 = '../data/anonymized_retweet_networks/2016/'
GRAPH_DIR_2020 = '../data/anonymized_retweet_networks/2020/'

biases = ['center', 'fake', 'left', 'right', 'left_leaning', 'right_leaning', 'left_extreme', 'right_extreme']


def format_graph_file(file, year):
    file = file.split('/')
    file = file[-1]
    file = file.split('.')
    return OUT_PATH + '/graphs/' + str(year) + '/' + file[0] + '_ci.gt'

def format_pickle_file(file, year, direction):
    file = file.split('/')
    file = file[-1]
    file = file.split('.')
    return OUT_PATH + '/output/' + str(year) + '/' + file[0] + '_' + direction + '_ci.pkl'

def add_CI_to_graph(file, year):

    print('pid ' + str(os.getpid()) + ' loading file ' + file)
    
    graph = gt.load_graph(file)
        
    for direction in ['out', 'in']:
        
        print('pid ' + str(os.getpid()) + ' -- ' + direction)
        t0 = time.time()
        CIranks, CImap = CIcython.compute_graph_CI(graph, rad=2,
                                          direction=direction,
                                          verbose=True)
        t1 = time.time() - t0
        
        print('pid ' + str(os.getpid()) + ' -- ' + str(t1))
        
        print('pid ' + str(os.getpid()) + ' saving CIranks ' + direction +  '_' + file.strip('.gt'))
        with open(format_pickle_file(file, year, direction), 'wb') as fopen:
            pickle.dump({'CIranks': CIranks, 'CImap' : CImap, 'time' : t1}, fopen)
    
        graph.vp['CI_' + direction] = graph.new_vertex_property('int64_t', vals=0)
        graph.vp['CI_' + direction].a = CImap
        
    print('pid ' + str(os.getpid()) + ' -- adding katz centrality')
    
    graph.vp['katz'] = gt.katz(graph)
    
    graph.set_reversed(True)
    graph.vp['katz_rev'] = gt.katz(graph)
    graph.set_reversed(False)
        
    graph_file = format_graph_file(file, year)

    # compute k_in and k_out for each node
    graph.vertex_properties['k_in'] = graph.new_vertex_property('int64_t')
    graph.vertex_properties['k_out'] = graph.new_vertex_property('int64_t')
    for v in graph.vertices():
        graph.vp.k_in[v] = v.in_degree()
        graph.vp.k_out[v] = v.out_degree()

    print('pid ' + str(os.getpid()) + ' saving graph ' + graph_file)
    graph.save(graph_file)

if __name__ == "__main__":
    if len(sys.argv) > 2:
        fname = sys.argv[1]
        year = sys.argv[2]

        # create output directory structure
        os.makedirs(os.path.join(OUT_PATH, 'graphs', '2016'), exist_ok=True)
        os.makedirs(os.path.join(OUT_PATH, 'graphs', '2020'), exist_ok=True)
        os.makedirs(os.path.join(OUT_PATH, 'output', '2016'), exist_ok=True)
        os.makedirs(os.path.join(OUT_PATH, 'output', '2020'), exist_ok=True)
        if fname != 'all':
            add_CI_to_graph(fname, year)

        else:
            print("Running for all.")
            for bias in biases:
                basepath = GRAPH_DIR_2016 if year == '2016' else GRAPH_DIR_2020
                name = os.path.join(basepath, '{}_{}.gt'.format(bias, year))
                add_CI_to_graph(name, year)